# Generated by Django 5.2.5 on 2025-08-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Client', 'Client'), ('Supplier', 'Supplier'), ('Admin', 'Admin')], default='Client', max_length=20),
        ),
    ]
