# Generated by Django 5.2.5 on 2025-08-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_supplier_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
